version: '3.8'
services:
  survival-prediction:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: titanic-survival-prediction
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1